### ISSUE TITLE
ER: Code enhancement for `add-label.js`

### ISSUE THREAD

**Issue by joey-ma** [hackforla/website#6840]
### Emergent Requirement - Problem

Since these are mostly enhancement changes, and my commits were not the cleanest so I'm including my reasonings below 👇🏻👇🏻👇🏻 

for `github-actions/utils/get-timeline.js`:
- [x] [add error handling for type error and retries](https://github.com/hackforla/ops/pull/123/commits/273d5899c7b21fa8748cdb756430aca1e219c3c4)

for `github-actions/trigger-schedule/add-update-label-weekly/add-label.js`:

- [ ] [refactor](https://github.com/hackforla/ops/pull/123/commits/c66626e08a30e8ab24b39b43cde23d5946bb0136)
  - [ ] purpose 1: to improve readability (ignore console log on line:47)
  - [ ] purpose 2: avoid getting following error (`login` exists for when response `event: 'assigned'`, but not when `event: 'committed'`, done in 2 commits, here's the other [commit](https://github.com/hackforla/ops/pull/123/commits/0d75a7ecca174e4d3319e1f1e10ab16d9ab8b316). Feel free to do a diff on this [file](https://github.com/hackforla/ops/blob/2b4ac464755bc16f75aff61f813c620f0d80babb/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) with the [existing file](https://github.com/hackforla/website/blob/aee5666a963d109b91c5d978a7e502998acd7e8f/github-actions/trigger-schedule/add-update-label-weekly/add-label.js))
```
TypeError: Cannot read properties of undefined (reading 'login')
|     at isTimelineOutdated (/Users/joeyma/Documents/GitHub/hfla/ops/github-actions/trigger-schedule/add-update-label-weekly/add-label.js:125:67)
|     at main (/Users/joeyma/Documents/GitHub/hfla/ops/github-actions/trigger-schedule/add-update-label-weekly/add-label.js:46:34)
|     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
- [ ] [refactor](https://github.com/hackforla/ops/pull/123/commits/fa5cb8762b07c3c2218c7bddf128263d7a3c940c)
  - [ ] purpose: to enhance logging and error handling, specifically to avoid getting the following error. This is when the request is attempting to delete a label that does not exist on the issue (responseObject). The `404` is then rather the expected behavior, so I opted to return a response object instead of the entire error message `Function failed to remove labels. Please refer to the error below: \n , err`, which otherwise alerted me that something is wrong and should be investigated.
```
Function failed to remove labels. Please refer to the error below: 
|   RequestError [HttpError]: Label does not exist
|     at /run/act/actions/actions-github-script@v7/dist/index.js:9537:21
|     at processTicksAndRejections (node:internal/process/task_queues:96:5)
|     at async removeLabels (/Users/joeyma/Documents/GitHub/hfla/ops/github-actions/trigger-schedule/add-update-label-weekly/add-label.js:193:19)
|     at async main (/Users/joeyma/Documents/GitHub/hfla/ops/github-actions/trigger-schedule/add-update-label-weekly/add-label.js:64:7) {
|   status: 404,
|   response: {
|     url: 'https://api.github.com/repos/joey-ma/ops/issues/1/labels/2%20weeks%20inactive',
|     status: 404,
|     headers: {
|       'access-control-allow-origin': '*',
|       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
|       'content-encoding': 'gzip',
|       'content-security-policy': "default-src 'none'",
|       'content-type': 'application/json; charset=utf-8',
|       date: 'Thu, 18 Apr 2024 07:03:37 GMT',
|       'github-authentication-token-expiration': '2024-04-19 08:08:11 -0700',
|       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
|       server: 'GitHub.com',
|       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
|       'transfer-encoding': 'chunked',
|       vary: 'Accept-Encoding, Accept, X-Requested-With',
|       'x-accepted-github-permissions': 'issues=write; pull_requests=write',
|       'x-content-type-options': 'nosniff',
|       'x-frame-options': 'deny',
|       'x-github-api-version-selected': '2022-11-28',
|       'x-github-media-type': 'github.v3; format=json',
|       'x-github-request-id': '865F:24CEF9:F4B6AC6:F5C7CF5:6620C5C8',
|       'x-ratelimit-limit': '5000',
|       'x-ratelimit-remaining': '4958',
|       'x-ratelimit-reset': '1713425713',
|       'x-ratelimit-resource': 'core',
|       'x-ratelimit-used': '42',
|       'x-xss-protection': '0'
|     },
|     data: {
|       message: 'Label does not exist',
|       documentation_url: 'https://docs.github.com/rest/issues/labels#remove-a-label-from-an-issue'
|     }
|   },
|   request: {
|     method: 'DELETE',
|     url: 'https://api.github.com/repos/joey-ma/ops/issues/1/labels/2%20weeks%20inactive',
|     headers: {
|       accept: 'application/vnd.github.v3+json',
|       'user-agent': 'actions/github-script octokit-core.js/5.0.1 Node.js/16.20.2 (linux; x64)',
|       authorization: 'token [REDACTED]'
|     },
|     request: {
|       agent: [Agent],
|       fetch: [Function: proxyFetch],
|       hook: [Function: bound bound register]
|     }
|   }
| }
```

### Issue you discovered this emergent requirement in
- DevOps repo issue https://github.com/hackforla/ops/issues/58

### Date discovered 
03/12/2024

### Did you have to do something temporarily
- [x] YES
- [ ] NO

### Who was involved
@joey-ma

### What happens if this is not addressed
N/A

### Recommended Action Items
- [ ] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]

`github-actions/utils/get-timeline.js`

```js
/**
 * Function that returns the issue's timeline of events.
 * https://octokit.github.io/rest.js/v20#issues-list-events-for-timeline
 * https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28#list-issue-events
 * @param {number} issue_number
 * @returns {Array} of Objects containing the issue's timeline of events
 */
async function getTimeline(issue_number, github, context) {
  const { owner, repo } = context.repo;
  let timelineArr = [];
  let page = 1, retries = 0;
  const per_page = 100, maxRetries = 3;

  while (true) {
    try {
      const { data } = await github.rest.issues.listEventsForTimeline({
        owner,
        repo,
        issue_number,
        per_page,
        page,
      });
      if (data.length) {
        timelineArr = timelineArr.concat(data);
        page++;
      } else {
        break;
      }
    } catch (err) {
      if (err instanceof TypeError) throw new Error(err);
      if (retries < maxRetries) {
        const delay = Math.pow(2, retries);
        console.log(`Retrying in ${delay} seconds...`);
        await new Promise(resolve => setTimeout(resolve, delay * 1000));
        retries++;
      } else {
        console.error(err);
        throw new Error(`Failed to fetch timeline for issue #${issue_number}`);
      }
    }
  }
  return timelineArr;
}

module.exports = getTimeline;
```

`github-actions/utils/find-linked-issue.js`

```js
/**
 * Function that returns a linked issue.
 * @param text the text to match keywords
 * @returns 
 */
function findLinkedIssue(text) {
    // Create RegEx for capturing KEYWORD #ISSUE-NUMBER syntax (i.e. resolves #1234)
    const KEYWORDS = ['close', 'closes', 'closed', 'fix', 'fixes', 'fixed', 'resolve', 'resolves', 'resolved']
    let reArr = [] // an array used to store multiple RegExp patterns
    for (const word of KEYWORDS) {
        reArr.push(`[\\n|\\s|^]${word} #\\d+\\s|^${word} #\\d+\\s|\\s${word} #\\d+$|^${word} #\\d+$`)
    }

    // Receive and unpack matches into an Array of Array objs
    let re = new RegExp(reArr.join('|'), 'gi')
    let matches = text.matchAll(re)
    matches = [...matches]

    // If only one match is found, return the issue number & console.log results.
    if (matches.length == 1) {
        const issueNumber = matches[0][0].match(/\d+/)
        return issueNumber[0]
    } else {
        return null
    }
}

module.exports = findLinkedIssue
```

`github-actions/trigger-schedule/add-update-label-weekly/add-label.js` at https://github.com/hackforla/ops/blob/2b4ac464755bc16f75aff61f813c620f0d80babb/github-actions/trigger-schedule/add-update-label-weekly/add-label.js

**Comment by t-will-gillis** [comment]
Created:
- [ ] #7105 
- [ ] #7080 (related)


A previous, unrelated refactor addressed the main problem, i.e.. the `RequestError [HttpError]: Label does not exist`, therefore no changes were made to address this error. Also, I decided not to address the cosmetic enhancements to `add-label.js` at this time since they are cosmetic.  

With the creation of the two issues, closing this ER.
